library(tidyverse)
movies = read_csv('https://raw.githubusercontent.com/r-classes/2020_da4l_hw5/master/data/MovieLens_films.csv')
## Задание 5.1.1
movies %>% 
  ggplot(aes(year, mean_rating, color = genres))+
  geom_point()+
  geom_smooth(method = "lm")+
  
  labs(x = "year",
       y = "mean_rating")

## Задание 5.1.2

fit <- lm(mean_rating ~ year + genres, data = movies)
summary(fit)

mean_rating (comedy) = 9.754755 + (-0.003160*year)
mean_rating (drama) = 9.754755 + (-0,003160*year) + 0.340926 = 10.0957
mean_rating (thriller) = 9.754755 + (-0,003160*year) + 0.105548 = 9.8603

#наибольший свободный член:
10.0957

## Задание 5.1.3

install.packages('ggeffects')
library(ggeffects)
plot(ggpredict(fit, terms = c("year", "genres")))

## Задание 5.1.4

comedy2007 <-  9.754755 + (-0.003160*2007) 
comedy2011 <-  9.754755 + (-0.003160*2011)
comedy2018 <-  9.754755 + (-0.003160*2018)

comedy2007 = 3.412635
comedy2011 = 3.399995
comedy2018 = 3.377875

## Задание 5.2

games = read_csv('https://raw.githubusercontent.com/r-classes/2020_da4l_hw5/master/data/board_games.csv')

## Задание 5.2.1 Визуализируйте связь между перемеными owned, average_rating и category (я использовал аргумент alpha = 0.2).ga

games%>%
  select(category, owned, average_rating) +
  ggplot(aes(owned, average_rating)) +
  scale_x_log10() +
  facet_wrap(~category) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm", se = TRUE)
  labs(x = "owned",
       y = "average_rating")

## Задание 5.2.2

fit0 <- lm(average_rating ~ owned + category, data = games)
  summary(fit0)

#average rating (bluffing) = 5.744e+00 + 7.641e-05*owned
#average rating (economic) = 5.744e+00 + 7.641e-05*owned + 1.993e-01
#average rating (fighting) = 5.744e+00 + 7.641e-05*owned + 8.178e-02
#average rating (science fiction) = 5.744e+00 + 7.641e-05*owned + 6.343e-02
...

#наибольший свободный член - 5.744e+00 + 7.641e-05*owned + 8.178e-02

...

## Задание 5.2.3

plot(ggpredict(fit0, terms = c("owned", "category")))

## Задание 5.2.4
owner1 <- 5.744e+00 + 7.641e-05*3000 + 1.993e-01
owner2 <- 5.744e+00 + 7.641e-05*5000 + 1.993e-01

owner1 = 6.17253
owner2 = 6.32535

## Задание 5.3
corals <- read_csv('https://raw.githubusercontent.com/r-classes/2020_da4l_hw5/master/data/deep_sea_corals.csv')

corals %>% 
  select(ScientificName, DepthInMeters) %>% 
  group_by(ScientificName, DepthInMeters) %>%
  count(ScientificName) %>% 
  ungroup() %>% 
  group_by(DepthInMeters) %>% 
  mutate(ratio = n/sum(n)) %>% 
  summarise(entropy = -sum(ratio*log2(ratio))) %>% 
  ggplot(aes(DepthInMeters, entropy)) +
  geom_point() +
  geom_smooth()+
  labs(x = "DepthInMeters",
       y = "entropy")

## Задание 5.4.1

Мы исследовали два наиболее распространненых вида кораллов (Heteropolypus ritteri и Lophelia pertusa) 
и обнаружили, что существует некоторый барьер обитания в 1000 метров ниже уровне моря для обитания вида 
Lophelia pertusa. Мы обнаружили, что ниже уровня 1000 метров вид Heteropolypus ritteri обитает значительно 
чаще чем Lophelia pertusa (χ2(1) = 36, p < 2.2e-16).

нулевая гипотеза: глубина не влияет на частоту встречаемости кораллов
Альтернативная: влияет

install.packages('statchek')
library(statcheck)

#ЗАДАНИЕ 5.4.1

check <- statcheck(c('χ2(1) = 36, p < 2.2e-16'))
check

computed p-value > 2.2e-16 (а p-value вроде бы должно быть меньше) 
#ЗАДАНИЕ 5.4.2

filtered <- corals%>%
  select(ScientificName, DepthInMeters)%>%
  filter(ScientificName == 'Heteropolypus ritteri' | ScientificName == 'Lophelia pertusa')%>%
  count(ScientificName, DepthInMeters)%>%
  group_by(ScientificName)%>%
  mutate(whole_num = sum(n))%>%
  filter(DepthInMeters > 1000)%>%
  group_by(ScientificName)%>%
  mutate(under_1000 = sum(n))

corals_stat <- matrix(c(3630, 15556-3630, 29, 14115-29), nrow = 2, 
                         byrow = TRUE, dimnames = list(c("Heteropolypus ritteri", "Lophelia pertusa"), 
                                                       c("Ниже 1000", "Выше 1000")))
chisq.test(corals_stat)

Отклоняем нулевую гипотезу с вероятностью ошибки при p-value < 2.2e-16.
